
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these are replica set labels
  labels:
    purpose: helm-demo
    project: roboshop
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: headless-svc-demo
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose: headless-svc-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
